version: '2'

services:

  redis:
    image: "redis:latest"

  zuul:
    build:
      context: ./zuul
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
        - eureka

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile


  postgres:
    image: "postgres:10"




