version: '2'

services:

  redis:
    image: "redis:latest"

  zuul:
    build:
      context: ./zuul
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
        - eureka

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - redis

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile

  highscore:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      depends_on:
        - redis

  postgres:
    image: "postgres:10"




