zuul:
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
      url: http://user-service:8080/
      sensitive-headers:

    highscore:
      path: /highscore/**
      serviceId: highscore-service
      url: http://highscore:8080/
      sensitive-headers:

    frontend:
      path: /frontend/**
      url: http://frontend/
      sensitive-headers:

    game:
      path: /game/**
      serviceId: game-service
      url: http://game:8080
      sensitive-headers:

    friendslist:
      path: /friendslist/**
      serviceId: friendslist-service
      url: http://friendslist:8080
      sensitive-headers:

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/



spring:
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379


security:
  sessions: ALWAYS



logging:
  level:
    org.springframework.security: debug