# Configuring here to use an actual database, whose IP address depends
# on where Docker Compose starts it


logging:
  level:
    org.springframework.security: debug

spring:
  application:
    name: game
  datasource:
    url: "jdbc:postgresql://postgres:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "update"

  redis:
    host: redis
    port: 6379
  session:
    # specify that session tokes should be stored in Redis
    store-type: redis

# Only the gateway should create a session.
security:
  sessions: NEVER

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

